ads/urls.py
from django.urls import path
from . import views
from .views import CarListView, CarDetailView, CarCreateView, CarUpdateView, CarDeleteView

urlpatterns = [
	path('', CarListView.as_view(), name='ads-home'),
	path('car/<int:pk>/', CarDetailView.as_view(), name='car-detail'),
	path('car/<int:pk>/update', CarUpdateView.as_view(), name='car-update'),
	path('car/<int:pk>/delete', CarDeleteView.as_view(), name='car-delete'),
	path('car/new/', CarCreateView.as_view(), name='car-create'),

]

carpalace/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ads.urls')),
    path('register/', user_views.register, name="register" ),
    path('profile/', user_views.profile, name="profile" ),
    path('profile/<int:pk>/', user_views.ProfileDetailView.as_view(), name='profile-detail'),
    path('profile_edit/', user_views.profile_edit, name="profile_edit" ),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Car(models.Model):
	name = models.CharField(max_length=255)
	price = models.DecimalField(max_digits=10, decimal_places=3)
	content = models.TextField()
	date_posted = models.DateTimeField(default=timezone.now)
	photo = models.ImageField(upload_to='cars')
	seller = models.ForeignKey(User, on_delete=models.CASCADE)


	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('ads-home'
		# kwargs={'pk': self.pk}
		)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE )
	date_joined = models.DateTimeField(default=timezone.now)
	profile_pic = models.ImageField(default="profile_pics/default.jpg", upload_to="profile_pics")
	about_me = models.TextField()

	def __str__(self):
		return f'{self.user.username} Profile'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()


	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['profile_pic', 'about_me']

ads/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Car

# Create your views here.
# def home(request):
# 	context = {
# 		'cars': Car.objects.all()
# 	}
# 	return render(request, 'ads/home.html', context)

class CarListView(ListView):
	 model = Car
	 template_name  = 'ads/home.html'
	 context_object_name = 'cars'
	 ordering = ['-date_posted']

class CarDetailView(DetailView):
	 model = Car

class CarCreateView(LoginRequiredMixin, CreateView):
	model = Car
	fields = ['name', 'price', 'content', 'photo']

	def form_valid(self, form):
		form.instance.seller = self.request.user
		return super().form_valid(form)

class CarUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Car
	fields = ['name', 'price', 'content', 'photo']

	def form_valid(self, form):
		form.instance.seller = self.request.user
		return super().form_valid(form)

	def test_func(self):
		car = self.get_object()
		if self.request.user == car.seller:
			return True
		return False

class CarDeleteView(LoginRequiredMixin, UserPassesTestMixin,  DeleteView):
	model = Car
	success_url = '/'

	def test_func(self):
		car = self.get_object()
		if self.request.user == car.seller:
			return True
		return False

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.views.generic import DetailView
from .models import Profile


def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'Account was successfuly created for {username}')
			return redirect('login')
	else:
		form = UserRegisterForm()
	return render(request, 'users/register.html', {'form': form})

@login_required
def profile(request):

	return render(request, 'users/profile.html')



@login_required
def profile_edit(request):
	if request.method == 'POST':
		u_form = UserUpdateForm(request.POST, instance=request.user)
		p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
		if u_form.is_valid() and p_form.is_valid():
			u_form.save()
			p_form.save()
			messages.success(request, f'Your account has been updated!')
			return redirect('profile')

	else:
		u_form = UserUpdateForm(instance=request.user)
		p_form = ProfileUpdateForm(instance=request.user.profile)

	context = {
	'u_form': u_form,
	'p_form': p_form
	}
	return render(request, 'users/profile_edit.html', context)


class ProfileDetailView(DetailView):
	model = Profile
	template_name = 'users/profile_detail.html'
	context_object_name = 'user'

ads/templates/ads/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'ads/main.css' %}">
    {% if title %}
	<title>{{title}}</title>
	{% endif %}
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{% url 'ads-home' %}">CarPalace</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">

          <!-- Navbar Right Side -->
          <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="{% url 'car-create' %}">Sell a Car</a>
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
            {% endif %}

          </div>
        </div>
      </div>
    </nav>
  </header>
	<main role="main" class="container">
  <div class="row">
    <div class="col-md-12">
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}"> {{ message }} </div>
      {% endfor %}
    {% endif %}
      {% block content %}{% endblock %}
    </div>
  </div>
</main>

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>

</html>

ads/templates/ads/car_confirm_delete.html
{% extends 'ads/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4"> Confirm Delete your Post? </legend>
			<h2> Are you sure you want to delete? {{ object.name }}</h2>
		</fieldset>
		<button class="btn btn-outline-danger" type="submit"> Delete </button>
		<a href="{% url 'car-detail' object.id%}" class="btn btn-outline-secondary ml-2"> Cancel </a>
	</form>

</div>
{% endblock %}

ads/templates/ads/car_detail.html
{% extends 'ads/base.html' %}

{% block content %}
	<article class="media content-section">
		<img class="rounded-circle article-img" src="{{ object.seller.profile.profile_pic.url }}" alt="">
		<div class="media-body">
		  <div class="article-metadata">
			<a class="mr-2" href="#">{{ object.seller }}</a>
			<small class="text-muted">{{ object.date_posted|date:"P d M Y (e)" }}</small>
			{% if object.seller == user %}
			<a href="{% url 'car-update' object.id %}" class="btn btn-secondary btn-sm mt-1 mb-1"> Update</a>
			<a href="{% url 'car-delete' object.id %}" class="btn btn-danger btn-sm mt-1 mb-1"> Delete </a>
			{% endif %}
		</div>
		  <h2 class="article-title">{{ object.name }}</h2>
		  <small class="text-danger">Price: ${{ object.price}}</small>
		  <p class="article-content">{{ object.content }}</p>
		  <p class="article-content"> Contact Seller at {{ object.seller.email }}</p>
		  <img class="img-fluid" src="{{ object.photo.url }}">
		</div>
	  </article>




{% endblock content%}

ads/templates/ads/car_form.html
{% extends 'ads/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4"> Post your car | Sell it online  </legend>
			{{ form|crispy }}
		</fieldset>
		<button class="btn btn-outline-info" type="submit"> Post </button>
	</form>
</div>
{% endblock %}

ads/templates/ads/home.html
{% extends 'ads/base.html' %}

{% block content %}
	{% for car in cars%}


	<article class="media content-section">
		<img class="rounded-circle article-img" src="{{ car.seller.profile.profile_pic.url }}" alt="">
		<div class="media-body">
		  <div class="article-metadata">
			<a class="mr-2" href="/profile/{{car.seller.profile.id}}">{{ car.seller }}</a>
			<small class="text-muted">{{ car.date_posted|date:"P d M Y (e)" }}</small>


		  </div>
		  <h2><a class="article-title" href="/car/{{ car.id }}">{{ car.name }}</a></h2>
		  <small class="text-danger">Price: ${{ car.price}}</small>

		  <img class="img-fluid" src="{{ car.photo.url }}">
		</div>
	  </article>
	{% endfor %}



{% endblock content%}

users/templates/users/login.html
{% extends 'ads/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
	<form method="POST">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4"> Log In </legend>
			{{ form|crispy }}
		</fieldset>
		<button class="btn btn-outline-info" type="submit"> Login </button>

		<small class="text-muted ml-2"> <a href="{% url 'password_reset' %}"> Forgot you Password? </a></small>
	</form>
	<div class="border-top pt-3">
		<small class="text-muted"> Need an account?
			<a href="{% url 'register' %}" class="ml-2">Sign UP</a>
		</small>
	</div>
</div>
{% endblock %}

users/templates/users/logout.html
{% extends 'ads/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<h2> You have been logged out</h2>

	<div class="border-top pt-3">
		<small class="text-muted">
			<a href="{% url 'login' %}" >Log In Again</a>
		</small>
	</div>

{% endblock %}

users/templates/users/password_reset.html
{% extends 'ads/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
	<form method="POST">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4"> Reset your Password </legend>
			{{ form|crispy }}
		</fieldset>
		<button class="btn btn-outline-info" type="submit"> Request a new password </button>
	</form>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'ads/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="alert alert-info">
	Your password has been change.
</div>
	<a href="{% url 'login' %}"> Please login </a>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'ads/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
	<form method="POST">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4"> Reset your Password </legend>
			{{ form|crispy }}
		</fieldset>
		<button class="btn btn-outline-info" type="submit"> Reset Password </button>
	</form>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'ads/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="alert alert-info">
	A password reset email has been sent
</div>

{% endblock %}

users/templates/users/profile.html
{% extends "ads/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.profile_pic.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          {% if user == user %}
          <a href="{% url 'profile_edit' %}" class="btn btn-info" role="button"> Edit </a>
			    {% endif %}

          <p class="text-secondary"> Joined on {{ user.profile.date_joined | date:"d M Y" }}</p>
          <p class="text-secondary">{{ user.email }}</p>
          <h3> About Me </h3>
          <p class="text-secondary">{{ user.profile.about_me }}</p>

            <h2 class="mr-auto"> Posts </h2>
            {% for u in user.car_set.all %}

             <!-- <div class="card-deck">
              <div class="card">
                <img class="card-img-top" src="{{ u.photo.url }}" alt="Car image">
                <div class="card-body">
                  <h5 class="card-title">{{ u.name }}</h5>
                  <p class="card-text"> {{ u.content }}.</p>
                  <p class="card-text"><small class="text-muted">Last updated {{ u.date_posted }}</small></p>
                </div>
              </div> -->
              <div class="card-group">
              <div class="card bg-light mb-3" style="width: 18rem;">
                <img class="card-img-top" src="{{ u.photo.url }}" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title">{{ u.name }}</h5>
                  <p class="card-text">{{ u.content }}</p>
                  <a href="/car/{{ u.id }}" class="btn btn-primary"> Read More</a>
                </div>
              </div>
            </div>
             {% endfor %}

        </div>

      </div>
      <!-- FORM HERE -->

    </div>
{% endblock content %}

users/templates/users/profile_detail.html
{% extends "ads/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ object.profile_pic.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ object.user }}</h2>
          {% if object.user == user %}
          <a href="{% url 'profile_edit' %}" class="btn btn-info" role="button"> Edit </a>
			    {% endif %}
          <p class="text-secondary"> Joined on {{ object.date_joined | date:"d M Y" }}</p>
          <p class="text-secondary">{{ object.email }}</p>
          <h3> About Me </h3>
          <p class="text-secondary">{{ object.about_me }}</p>

            <h2 class="mr-auto"> Posts </h2>
            {% for u in object.user.car_set.all %}
              <div class="card-group">
              <div class="card bg-light mb-3" style="width: 18rem;">
                <img class="card-img-top" src="{{ u.photo.url }}" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title">{{ u.name }}</h5>
                  <p class="card-text">{{ u.content }}</p>
                  <a href="/car/{{ u.id }}" class="btn btn-primary"> Read More</a>
                </div>
              </div>
            </div>
             {% endfor %}

        </div>

      </div>
      <!-- FORM HERE -->

    </div>
{% endblock content %}

users/templates/users/profile_edit.html
{% extends "ads/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.profile_pic.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>

          <a href="{% url 'profile_edit' %}" class="btn btn-info" role="button"> Edit </a>

          <p class="text-secondary"> Joined on {{ user.date_joined | date:"d M Y" }}</p>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <!-- FORM HERE -->
	  <form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4"> Update Details</legend>
			{{ u_form|crispy }}
			{{ p_form|crispy }}
		</fieldset>
		<button class="btn btn-outline-info" type="submit"> Update </button>
		<a href="{% url 'profile' %}" class="btn btn-info ml-3" role="button"> Cancel </a>
	</form>

    </div>
{% endblock content %}

users/templates/users/register.html
{% extends 'ads/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
	<form method="POST">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4"> Join Us</legend>
			{{ form|crispy }}
		</fieldset>
		<button class="btn btn-outline-info" type="submit"> Sign Up </button>
	</form>
	<div class="border-top pt-3">
		<small class="text-muted"> Do you have an account?
			<a href="{% url 'login' %}" class="ml-2">LogIn</a>
		</small>
	</div>
</div>
{% endblock %}